# SimpleChat by Harry5573 configuration
# 
# Prefix = Prefix to use before messages
prefix: '&3[&eSimple&cChat&3]'
#
# Should we stop players chatting untill they have moved? (Anti BOT)
blockchatuntilmoved: true
#
# Should we block duplicate messages?
blockdupemsg: true
#
# Set the delay between messages (in seconds)
delay: 3
#
# AntiAdvertising Settings
#
# If someone postes an ip shall we ban them after a warning?
banip: true
#
# If someone postes a url shall we ban them after a warning?
banweb: true
#
# Website to use for the ban message
website: 'www.arkhamnetwork.org'