# SimpleChat by Harry5573 configuration
# 
# Prefix = Prefix to use before messages
prefix: '&8[&cArkhamChat&8]'
#
# Should we stop players chatting untill they have moved? (Anti BOT)
blockchatuntilmoved: true
#
# Should we block duplicate messages?
blockdupemsg: true
#
# AntiAdvertising Settings
#
# If someone postes an ip shall we ban them after a warning?
banip: true
#
# If someone postes a url shall we ban them after a warning?
banweb: true
#
# Website to use for the ban message
website: 'www.arkhamnetwork.org'